# Generated by Django 6.0 on 2025-12-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leaverequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='to_date',
        ),
    ]
